name: DEPLOY PROD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Copia arquivos [repo(main) -> servidor]
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "3.232.236.192"
          REMOTE_USER: "ubuntu"
          TARGET: "/home/ubuntu/DEPLOY_VISIONBACK_PRD"
          SCRIPT_BEFORE: ls
          #SCRIPT_AFTER: exec ~/DEPLOY_SCRIPTS/docker_build.sh
          SCRIPT_AFTER: cd ~/VisionBackBuild && docker-compose up --build -d
